bond/urls.py
from django.conf.urls import patterns, include, url
# from bond.meetup.views import EventDetail, EventList
from django.contrib.auth.decorators import login_required
from haystack.forms import FacetedSearchForm
from haystack.query import SearchQuerySet
from haystack.views import search_view_factory, FacetedSearchView
from rest_framework import viewsets, routers
from rest_framework import permissions
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib import admin

from oauth2_provider.ext.rest_framework import TokenHasReadWriteScope, TokenHasScope

from apps.meetup.models import Event
from apps.meetup.views import EventList, EventDetail

# ViewSets define the view behavior.
# class EventViewSet(viewsets.ModelViewSet):
#     permission_classes = [permissions.IsAuthenticated, TokenHasReadWriteScope]
#     model = Event
#
# # Routers provide an easy way of automatically determining the URL conf
# router = routers.DefaultRouter()
# router.register(r'events', EventViewSet)

# Faceting for Haystack:ES
sqs = SearchQuerySet().facet('city')

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'bond.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       url(r'^bondinfinity/', include(admin.site.urls)),
                       url(r'^bondinfinity/doc', include('django.contrib.admindocs.urls')),

                       url(r'^api/events/$', EventList.as_view(), name='event_list'),
                       url(r'^api/events/(?P<pk>[0-9]+)/$', EventDetail.as_view(), name='event_detail'),

                       # (r'^accounts/', include('registration.backends.default.urls')),

                       # added login and reset password to defaults

                       url('', include('social.apps.django_app.urls', namespace='social')),

                       url(r'^$', "apps.profiles.views.home", name="home"),
                       url(r'^about/$', 'apps.profiles.views.about', name='about'),
                       url(r'^why-us/$', 'apps.profiles.views.whyus', name='whyus'),
                       url(r'^login/$', 'apps.profiles.views.login', name='login'),

                       url(r'^contact/$', 'apps.contact.views.contact', name='contact'),

                       url(r'^profile/$', 'apps.profiles.views.profile', name='profile'),

                       url(r'^getting-started/$', 'apps.profiles.views.getting_started', name='getting_started'),

                       url(r'^settings/$', 'apps.profiles.views.settings', name='settings'),
                       url(r'^settings/(?P<interest_id>\w+)/delete/$', 'apps.profiles.views.delete_interest',
                           name='delete_interest'),

                       url(r'^settings/(?P<usercity_id>\w+)/$', 'apps.profiles.views.delete_user_city',
                           name='delete_city'),
                       # url(r'^meetup_all/$', 'meetup.tasks.meetup_api_find_open_events', name='all_open_event'),

                       url(r'^meetup-oauth/$', 'apps.meetup.views.meetup_oauth_connect', name='all_open_event'),

                       # url(r'^eventbrite_all/$', 'eventbrite.views.eventbrite', name='all_eventbrite_event'),
                       # url(r'^eventbrite_all/$', 'apps.eventbrite.views.eventbriteOAuth', name='all_eventbrite_event'),

                       url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),

                       url(r'^events/$', 'apps.events.views.events', name='events'),

                       url(r'^map/$', 'apps.maps.views.event_maps', name='map'),
                       url(r'^get-events/$', 'apps.maps.views.get_events', name='get_events'),

                       url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
                       url(r'^logout/$', 'apps.profiles.views.logout', name='logout'),

                       url(r'^a/$', 'apps.profiles.views.angular', name='angular'),

                       url(r'^search/$', include('apps.search.urls')),

                       # pulls urls from the haystack app
                       # url(r'^search/$', 'apps.meetup.views.autocomplete', name='autocomplete'),
                       # pulls urls from the haystack app
                       url(r'^search/category/$', search_view_factory(searchqueryset=SearchQuerySet().facet('city'),
                                                                      view_class=FacetedSearchView,
                                                                      form_class=FacetedSearchForm),
                                                                      name='faceted_search'),

)

urlpatterns = format_suffix_patterns(urlpatterns)

apps/profiles/forms.py
from crispy_forms.helper import FormHelper
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
# from djangular.forms import NgFormValidationMixin, NgModelFormMixin
from apps.profiles.models import Interest, Profile, UserCity


class ProfileCreationForm(UserCreationForm):
    """
   A form that we can use to create a patron with no privileges

   Use this form to create user simply by admin settings through the use of username & password
   """
    # Thanks to http://stackoverflow.com/questions/16953302/ for the solution to this one
    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            Profile._default_manager.get(username=username)
        except Profile.DoesNotExist:
            return username
        raise forms.ValidationError(
            self.error_messages['duplicate_username'],
            code='duplicate_username',
        )

    class Meta(UserCreationForm.Meta):
        model = get_user_model()  # 4b


class InterestForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(InterestForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Interest
        exclude = ['profile']


class ProfileForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'email', 'phone', 'city',
                  'email_notification', 'text_notification', 'zip_code',
                  'distance', 'notice_frequency']


class UserCityForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserCityForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = UserCity
        exclude = ['profile']


class GettingStartedForm(forms.Form):
    choices = (
        (3, "Strongly Agree"),
        (2, "Agree"),
        (1, "Disagree"),
        (0, "Strongly Disagree"),
    )

    One = forms.TypedChoiceField(choices=choices, coerce=int, widget=forms.RadioSelect,
                                 label="I attend food events in my community frequently")
    Two = forms.TypedChoiceField(choices=choices, coerce=int, widget=forms.RadioSelect,
                                 label="Physical well-being is important to me")
    Three = forms.TypedChoiceField(choices=choices, coerce=int, widget=forms.RadioSelect,
                                   label="I am currently seeking to build a stronger community/network")
    Four = forms.TypedChoiceField(choices=choices, coerce=int, widget=forms.RadioSelect,
                                  label="Attending conferences, "
                                        "workshops, and/or talks are important to my personal growth")
    Five = forms.TypedChoiceField(choices=choices, coerce=int, widget=forms.RadioSelect,
                                  label="I am more likely to attend an event if my friends will partake")
    Six = forms.TypedChoiceField(choices=choices, coerce=int, widget=forms.RadioSelect,
                                 label="I spend most of my free time with friends and families")
    Seven = forms.TypedChoiceField(choices=choices, coerce=int, widget=forms.RadioSelect,
                                   label="My preferred style of learning is hands-on rather than theoretical")
    Eight = forms.TypedChoiceField(choices=choices, coerce=int, widget=forms.RadioSelect,
                                   label="I enjoy planning my schedule in advance")
    Nine = forms.TypedChoiceField(choices=choices, coerce=int, widget=forms.RadioSelect,
                                  label="I personally enjoy participating in philanthropic events")
    Ten = forms.TypedChoiceField(choices=choices, coerce=int, widget=forms.RadioSelect,
                                 label="I know quite a bit about economic issues and personal investing.")
    Eleven = forms.TypedChoiceField(choices=choices, coerce=int, widget=forms.RadioSelect,
                                    label="I involve myself in competitive sports")
    Twelve = forms.TypedChoiceField(choices=choices, coerce=int, widget=forms.RadioSelect,
                                    label="I tend to have a lot of free time in a given week")

    helper = FormHelper()

templates/angular.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}

	<script src="{% static "js/angular.js" %}"></script>
	<script src="{% static "js/angular-resource.js" %}"></script>
    <script src="{% static "js/angular-route.js" %}"></script>
    <script src="{% static "js/app.js" %}"></script>

    <script src="{% static "js/controllers/indexController.js" %}"></script>
    <script src="{% static "js/controllers/startSurveyController.js" %}"></script>

{% endblock head %}

{% block content %}
	<div class="spacing-buffer"></div>
	<div class="container">
		<div class="row">
			<div ng-app="surveyApp">
				<a href="#/survey">Survey Page</a>
		           <ng-view class="appSection">


		           </ng-view>
		    </div>
		</div>
	</div>
{% endblock content %}

templates/base.html
{% load staticfiles %}
{% load compress %}

<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<meta name="description" content="Event curation through user interests.">
<link rel="icon" type="image/png" href="#" />
<link rel="author" href="http://www.bondandme.com" />
<link rel="publisher" href="http://www.bondandme.com"/>
<meta name="geo.region" content="US-CA" />
<meta name="geo.placename" content="San Francisco" />

<title>{% block title %}{% endblock title %}</title>
{#{% compress css %}#}
<!-- Custom CSS -->
<link href="{% static 'stylesheets/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'stylesheets/font-awesome.min.css' %}" rel="stylesheet">
<link href="{% static 'stylesheets/carousel.css' %}" rel="stylesheet">
<link href="{% static 'stylesheets/custom.css' %}" rel="stylesheet">
{#{% endcompress css %}#}
{% compress js %}
<script src="{% static 'js/jquery-1.11.0.min.js' %}"></script>
<script src="{% static 'js/modernizr.custom.14652.js' %}"></script>
<script src="{% static 'js/oauth.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
{#<script src="{% static '/Users/htm/Documents/bond/bower_components/components/notify.js/notify.js' %}"></script>#}
<script src="{% static 'js/notify.min.js' %}"></script>
{#<script src="{% static 'easytz/js/easytz.js' %}"></script>#}
<script src="{% static 'js/custom.js' %}"></script>
{% endcompress js %}
<script type="text/javascript">
    if (window.location.hash && window.location.hash == '#_=_') {
        window.location.hash = '';
    }
</script>

{% block head %}
	{% compress js %}
		<script async src="{% static 'js/picturefill.js' %}"></script>
	{% endcompress js %}
{% endblock head %}

</head>

<body id="home">

{% include 'navbar.html' %}
<div class="spacing-buffer"></div>
<div class="header-image">

	{% block headline %}

    {% endblock headline %}

</div><!-- /header-image -->



	<!-- START THE FEATURETTES -->
	{% block carousel %}

    {% endblock carousel %}

    {% block message %}

    {% endblock message %}

	{% block content %}

    {% endblock content %}

    {% block content_two %}

    {% endblock content_two %}


    {% block end_script %}


    {% endblock end_script %}


	<!-- /END THE FEATURETTES -->

	<!-- FOOTER -->
    <div class="footer">
        <div class="container">
            {% include 'footer.html' %}
        </div>
    </div>
    <!-- /END OF FOOTER -->



<!-- javascript -->
{#<script src="{% static 'js/jquery.js' %}"></script>#}


<!-- Custom SCRIPT -->
{% block script %}

{% endblock script %}


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54078693-1', 'auto');
  ga('send', 'pageview');

</script>

</body>

</html>

templates/getting_started.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="spacing-buffer"></div>
<div class="container">
	<h1 class="text-center">Ultimate event curation awaits after survey completion!</h1>
	<div class="spacing-buffer"></div>
	<div class="row col-lg-6 offset3">
		<form method='post' action=".">
        {% csrf_token %}
		 <div class="questSetOne">
			 <div class="img-responsive"><img src="{% static 'img/food_1.jpg' %}" class="img-circle" alt="Food"/></div>
	    <p>
		    <label for="id_One_0"><strong><h3>I attend food events in my community frequently</h3></strong></label>
			 <ul id="id_One">
				<li><label for="id_One_0"><input id="id_One_0" name="One" type="radio" value="3" /> Strongly Agree</label></li>
				<li><label for="id_One_1"><input id="id_One_1" name="One" type="radio" value="2" /> Agree</label></li>
				<li><label for="id_One_2"><input id="id_One_2" name="One" type="radio" value="1" /> Disagree</label></li>
				<li><label for="id_One_3"><input id="id_One_3" name="One" type="radio" value="0" /> Strongly Disagree</label></li>
			</ul>
		 </p>
             <div class="img-responsive"><img src="{% static 'img/wellbeing_1.jpg' %}" class="img-circle" alt="Wellbeing"/></div>
		<p>
			<label for="id_Two_0"><strong><h3>Physical well-being is important to me</h3></strong></label>
			<ul id="id_Two">
				<li><label for="id_Two_0"><input id="id_Two_0" name="Two" type="radio" value="3" /> Strongly Agree</label></li>
				<li><label for="id_Two_1"><input id="id_Two_1" name="Two" type="radio" value="2" /> Agree</label></li>
				<li><label for="id_Two_2"><input id="id_Two_2" name="Two" type="radio" value="1" /> Disagree</label></li>
				<li><label for="id_Two_3"><input id="id_Two_3" name="Two" type="radio" value="0" /> Strongly Disagree</label></li>
			</ul>
		</p>
			<div class="img-responsive"><img src="{% static 'img/networking_1.jpg' %}" class="img-circle" alt="Network"/></div>
		<p>
			<label for="id_Three_0"><strong><h3>I am currently seeking to build a stronger community/network</h3></strong></label>
			 <ul id="id_Three">
				<li><label for="id_Three_0"><input id="id_Three_0" name="Three" type="radio" value="3" /> Strongly Agree</label></li>
				<li><label for="id_Three_1"><input id="id_Three_1" name="Three" type="radio" value="2" /> Agree</label></li>
				<li><label for="id_Three_2"><input id="id_Three_2" name="Four" type="radio" value="1" /> Disagree</label></li>
				<li><label for="id_Three_3"><input id="id_Three_3" name="Four" type="radio" value="0" /> Strongly Disagree</label></li>
			</ul>
		</p>
			 <div class="img-responsive"><img src="{% static 'img/apple_1.jpg' %}" class="img-circle" alt="Network"/></div>
		<p>
			<label for="id_Four_0"><strong><h3>Attending conferences, workshops, and/or talks are important to my personal growth</h3></strong></label>
			 <ul id="id_Four">
				<li><label for="id_Four_0"><input id="id_Four_0" name="Four" type="radio" value="3" /> Strongly Agree</label></li>
				<li><label for="id_Four_1"><input id="id_Four_1" name="Four" type="radio" value="2" /> Agree</label></li>
				<li><label for="id_Four_2"><input id="id_Four_2" name="Four" type="radio" value="1" /> Disagree</label></li>
				<li><label for="id_Four_3"><input id="id_Four_3" name="Four" type="radio" value="0" /> Strongly Disagree</label></li>
			</ul>
		</p>
		<a href="#" class="btn btn-xl cente questSetOneNext">Next</a>
		</div>
		<div class="questSetTwo" style="display: none;">
			 <div class="img-responsive"><img src="{% static 'img/motivation_1.jpg' %}" class="img-circle" alt="Network"/></div>
		<p>
			<label for="id_Five_0"><strong><h3>I am more likely to attend an event if my friends will partake</h3></strong></label>
				<ul id="id_Five">
					<li><label for="id_Five_0"><input id="id_Five_0" name="Five" type="radio" value="3" /> Strongly Agree</label></li>
					<li><label for="id_Five_1"><input id="id_Five_1" name="Five" type="radio" value="2" /> Agree</label></li>
					<li><label for="id_Five_2"><input id="id_Five_2" name="Five" type="radio" value="1" /> Disagree</label></li>
					<li><label for="id_Five_3"><input id="id_Five_3" name="Five" type="radio" value="0" /> Strongly Disagree</label></li>
				</ul>
		</p>
			 <div class="img-responsive"><img src="{% static 'img/family_1.jpg' %}" class="img-circle" alt="Network"/></div>
		<p>
			<label for="id_Six_0"><strong><h3>I spend most of my free time with friends and families</h3></strong></label>
			<ul id="id_Six">
				<li><label for="id_Six_0"><input id="id_Six_0" name="Six" type="radio" value="3" /> Strongly Agree</label></li>
				<li><label for="id_Six_1"><input id="id_Six_1" name="Six" type="radio" value="2" /> Agree</label></li>
				<li><label for="id_Six_2"><input id="id_Six_2" name="Six" type="radio" value="1" /> Disagree</label></li>
				<li><label for="id_Six_3"><input id="id_Six_3" name="Six" type="radio" value="0" /> Strongly Disagree</label></li>
			</ul>
		</p>
			 <div class="img-responsive"><img src="{% static 'img/making_1.jpg' %}" class="img-circle" alt="Network"/></div>
		<p>
			<label for="id_Seven_0"><strong><h3>My preferred style of learning is hands-on rather than theoretical</h3></strong></label>
			<ul id="id_Seven">
				<li><label for="id_Seven_0"><input id="id_Seven_0" name="Seven" type="radio" value="3" /> Strongly Agree</label></li>
				<li><label for="id_Seven_1"><input id="id_Seven_1" name="Seven" type="radio" value="2" /> Agree</label></li>
				<li><label for="id_Seven_2"><input id="id_Seven_2" name="Seven" type="radio" value="1" /> Disagree</label></li>
				<li><label for="id_Seven_3"><input id="id_Seven_3" name="Seven" type="radio" value="0" /> Strongly Disagree</label></li>
			</ul>
		</p>
			 <div class="img-responsive"><img src="{% static 'img/calendar_1.png' %}" class="img-circle" alt="Network"/></div>
		<p>
			<label for="id_Eight_0"><strong><h3>I enjoy planning my schedule in advance</h3></strong></label>
			<ul id="id_Eight">
				<li><label for="id_Eight_0"><input id="id_Eight_0" name="Eight" type="radio" value="0" /> Strongly Agree</label></li>
				<li><label for="id_Eight_1"><input id="id_Eight_1" name="Eight" type="radio" value="1" /> Agree</label></li>
				<li><label for="id_Eight_2"><input id="id_Eight_2" name="Eight" type="radio" value="2" /> Disagree</label></li>
				<li><label for="id_Eight_3"><input id="id_Eight_3" name="Eight" type="radio" value="3" /> Strongly Disagree</label></li>
			</ul>
		</p>
		<a href="#" class="btn btn-xl centered questSetTwoNext">Next</a>
		</div>
		<div class="questSetThree" style="display: none;">
			<div class="img-responsive"><img src="{% static 'img/community_1.jpg' %}" class="img-circle" alt="Network"/></div>
		<p>
			<label for="id_Nine_0"><strong><h3>I personally enjoy participating in philanthropic events</h3></strong></label>
			<ul id="id_Nine">
				<li><label for="id_Nine_0"><input id="id_Nine_0" name="Nine" type="radio" value="3" /> Strongly Agree</label></li>
				<li><label for="id_Nine_1"><input id="id_Nine_1" name="Nine" type="radio" value="2" /> Agree</label></li>
				<li><label for="id_Nine_2"><input id="id_Nine_2" name="Nine" type="radio" value="1" /> Disagree</label></li>
				<li><label for="id_Nine_3"><input id="id_Nine_3" name="Nine" type="radio" value="0" /> Strongly Disagree</label></li>
			</ul>
		</p>
			<div class="img-responsive"><img src="{% static 'img/competitive_1.jpg' %}" class="img-circle" alt="Network"/></div>
		<p>
			<label for="id_Ten_0"><strong><h3>I involve myself in competitive sports</h3></strong></label>
			<ul id="id_Ten">
				<li><label for="id_Ten_0"><input id="id_Ten_0" name="Ten" type="radio" value="3" /> Strongly Agree</label></li>
				<li><label for="id_Ten_1"><input id="id_Ten_1" name="Ten" type="radio" value="2" /> Agree</label></li>
				<li><label for="id_Ten_2"><input id="id_Ten_2" name="Ten" type="radio" value="1" /> Disagree</label></li>
				<li><label for="id_Ten_3"><input id="id_Ten_3" name="Ten" type="radio" value="0" /> Strongly Disagree</label></li>
			</ul>
		</p>
			<div class="img-responsive"><img src="{% static 'img/time.jpg' %}" class="img-circle" alt="Network"/></div>
		<p>
			<label for="id_Eleven_0"><strong><h3>I tend to have a lot of free time in a given week</h3></strong></label>
			<ul id="id_Eleven">
				<li><label for="id_Eleven_0"><input id="id_Eleven_0" name="Eleven" type="radio" value="3" /> Strongly Agree</label></li>
				<li><label for="id_Eleven_1"><input id="id_Eleven_1" name="Eleven" type="radio" value="2" /> Agree</label></li>
				<li><label for="id_Eleven_2"><input id="id_Eleven_2" name="Eleven" type="radio" value="1" /> Disagree</label></li>
				<li><label for="id_Eleven_3"><input id="id_Eleven_3" name="Eleven" type="radio" value="0" /> Strongly Disagree</label></li>
			</ul>
		</p>
			<div class="img-responsive"><img src="{% static 'img/risk_1.jpg' %}" class="img-circle" alt="Network"/></div>
		<p>
			<label for="id_Twelve_0"><strong><h3>I enjoy trying risk and trying new things</h3></strong></label>
			<ul id="id_Twelve">
				<li><label for="id_Twelve_0"><input id="id_Twelve_0" name="Twelve" type="radio" value="3" /> Strongly Agree</label></li>
				<li><label for="id_Twelve_1"><input id="id_Twelve_1" name="Twelve" type="radio" value="2" /> Agree</label></li>
				<li><label for="id_Twelve_2"><input id="id_Twelve_2" name="Twelve" type="radio" value="1" /> Disagree</label></li>
				<li><label for="id_Twelve_3"><input id="id_Twelve_3" name="Twelve" type="radio" value="0" /> Strongly Disagree</label></li>
			</ul>
		</p>

{#		<a href="#" class="btn btn-xl questSetThreeNext">Next</a>#}

{#		</div>#}
{#		<div class="questSetFour" style="display: none;">#}
{#		<p><label for="id_Thirteen_0"><strong><h3>Blah</h3></strong></label> <ul id="id_Thirteen">#}
{#		<li><label for="id_Thirteen_0"><input id="id_Thirteen_0" name="Thirteen" type="radio" value="-3" /> YES</label></li>#}
{#		<li><label for="id_Thirteen_1"><input id="id_Thirteen_1" name="Thirteen" type="radio" value="3" /> NO</label></li>#}
{#		</ul></p>#}
{#		<p><label for="id_Fourteen_0"><strong><h3>Blah</h3></strong></label> <ul id="id_Fourteen">#}
{#		<li><label for="id_Fourteen_0"><input id="id_Fourteen_0" name="Fourteen" type="radio" value="3" /> YES</label></li>#}
{#		<li><label for="id_Fourteen_1"><input id="id_Fourteen_1" name="Fourteen" type="radio" value="-3" /> NO</label></li>#}
{#		</ul></p>#}
{#		<p><label for="id_Fifteen_0"><strong><h3>Blah</h3></strong></label> <ul id="id_Fifteen">#}
{#		<li><label for="id_Fifteen_0"><input id="id_Fifteen_0" name="Fifteen" type="radio" value="3" /> YES</label></li>#}
{#		<li><label for="id_Fifteen_1"><input id="id_Fifteen_1" name="Fifteen" type="radio" value="-3" /> NO</label></li>#}
{#		</ul></p>#}
{#		<p><label for="id_Sixteen_0"><strong><h3>Blah</h3></strong></label> <ul id="id_Sixteen">#}
{#		<li><label for="id_Sixteen_0"><input id="id_Sixteen_0" name="Sixteen" type="radio" value="3" /> Strongly Agree</label></li>#}
{#		<li><label for="id_Sixteen_1"><input id="id_Sixteen_1" name="Sixteen" type="radio" value="2" /> Agree</label></li>#}
{#		<li><label for="id_Sixteen_2"><input id="id_Sixteen_2" name="Sixteen" type="radio" value="1" /> Disagree</label></li>#}
{#		<li><label for="id_Sixteen_3"><input id="id_Sixteen_3" name="Sixteen" type="radio" value="0" /> Strongly Disagree</label></li>#}
{#		</ul></p>#}
		    <input class="btn btn-primary" type='submit' value='Submit'>
	    </div>
		</form>
	</div>
</div>


{% endblock %}

templates/navbar.html
<div class="navbar navbar-fixed-top">
	<div class="container">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
        <div id="top-menu">
            {% if user.is_authenticated %}
                <a class="navbar-brand" href="{% url 'profile' %}">Bond<img class="logo" src="" /></a>
            {% else %}
                <a class="navbar-brand" href="{% url 'home' %}">Bond<img class="logo" src="" /></a>
            {% endif %}
			<div class="nav-collapse collapse">
				<ul class="nav navbar-nav pull-right">
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'profile' %}">Profile</a></li>
                        <li><a href="{% url 'haystack_search' %}">Event Search  <i class="fa fa-search"></i></a></li>
                        <li><a href="{% url 'settings' %}">Settings</a></li>

                    {% else %}
{#					<li><a href="{% url 'home' %}">Home</a></li>#}
                        <li><a href="{% url 'about' %}">About</a></li>
{#                        <li><a href={% url 'whyus' %}#">Why Us?</a></li>#}
                    {% endif %}


					<li><a href="{% url 'contact' %}" title="We love your thoughts!!">Contact</a></li>
                    {% if user.is_authenticated %}
                        <li class="active"><a href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
{#                        <li><a href="{% url 'register' %}">Register</a></li>#}
                        <li class="active"><a href="{% url 'login' %}">Log In</a></li>
                    {% endif %}
				</ul>
            </div>
		</div><!--/nav-collapse -->
	</div>
</div><!-- /navbar-fixed-top -->